### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZR-00** [CJMinecraft01/ReloadAudioDriverForge#2]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/26/20 4:11 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.KeyboardListener.field_197975_d from class cjminecraft.rad.ReloadAudioDriver
	at cjminecraft.rad.ReloadAudioDriver.onKeyInputEvent(ReloadAudioDriver.java:33) ~[?:3.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_68_ReloadAudioDriver_onKeyInputEvent_KeyInputEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:798) ~[?:?] {re:classloading}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:399) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$5779/894754374.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:398) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$1990/646559570.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(SourceFile:301) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.48.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/246014273.call(Unknown Source) [forge-1.15.2-31.1.48.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cjminecraft.rad.ReloadAudioDriver.onKeyInputEvent(ReloadAudioDriver.java:33)
	at net.minecraftforge.eventbus.ASMEventHandler_68_ReloadAudioDriver_onKeyInputEvent_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:798)
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:364)
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:399)
	at net.minecraft.client.KeyboardListener$$Lambda$5779/894754374.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:398)
	at net.minecraft.client.KeyboardListener$$Lambda$1990/646559570.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Ergazu'/32, l='MpServer', x=-89.70, y=79.00, z=-165.76]]
	Chunk stats: Client Chunk Cache: 1225, 918
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 6756989695361253803
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-2,237,-39), Chunk: (at 14,14,9 in -1,-3; contains blocks -16,0,-48 to -1,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 34976 game time, 34976 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/246014273.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 609335472 bytes (581 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.48
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.48-client.jar Minecraft {minecraft@1.15.2 DONE}
		Ageing-Mobs-1.15.2-1.0.0.jar Ageing Mobs Mod {ageingmobs@1.0.0 DONE}
		Ma-Enchants-1.15.2-3.1.0.jar Ma Enchants {ma-enchants@1.15.2-3.1.0 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		Dynamite.jar Dynamite {dynamite@1.0.4 DONE}
		astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		rad-1.15-3.0.0.jar Reload Audio Driver {rad@3.0.0 DONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 DONE}
		Craftable+Saddles+[1.15.2]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		curios-FORGE-1.15.2-2.0.2.1.jar Curios API {curios@FORGE-1.15.2-2.0.2.1 DONE}
		tetra-1.15.2-2.5.0.jar Tetra {tetra@1.15.2-2.5.0 DONE}
		Neat+1.6-20.jar Neat {neat@1.6-20 DONE}
		ForgeEndertech-1.15.2-6.0.2.1-build.0024.jar Forge Endertech {forgeendertech@6.0.2.1 DONE}
		AdFinders-1.15.2-4.0.5.0-build.0020.jar Advanced Finders {adfinders@4.0.5.0 DONE}
		AdLods-1.15.2-3.0.2.0-build.0029.jar Large Ore Deposits {adlods@3.0.2.0 DONE}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		PyramidPlunder-1.15.2-1.0.jar Pyramid Plunder {pyramidplunder@1.15-1.0 DONE}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 DONE}
		guardvillagers-1.15.2-1.0.6.jar Guard Villagers {guardvillagers@1.0.6 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Charm-1.15.2-1.5.7.jar Charm {charm@1.15.2-1.5.7 DONE}
		branders-sulfurpotassiummod-1.15.2-2.3.0.jar Sulfur And Potassium - make gunpowder {sulfurpotassiummod@2.3.0 DONE}
		forge-1.15.2-31.1.48-universal.jar Forge {forge@31.1.48 DONE}
		ScalingHealth-1.15.2-3.0.3+52.jar Scaling Health {scalinghealth@3.0.3+52 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CosmeticArmorReworked-1.15.2-v2.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v2 DONE}
		exp_bottling-1.15.2-1.jar EXP Bottling {exp_bottling@1.15.2-1 DONE}
		luckyore_1.15.2-1.2.2.jar Lucky Ore {luckyore@1.2.2 DONE}
	Launched Version: 1.15.2-forge-31.1.48
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce 940M/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/OreOverhaulRelease_1.7.zip, file/Prime.zip, mod_resources
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

**Comment by CJMinecraft01** [comment]
Fixed in the latest version!
